# logo: "/assets/images/just-the-docs.png"
title: Worldbuilding
description: A portfolio of worldbuilding with two worlds.
theme: just-the-docs

url: https://syazwaniMZ.github.io/dual-worldbuilding.github.io

aux_links:
  Worldbuilding Repository: https://github.com/syazwaniMZ/dual-worldbuilding.github.io

color_scheme: nil

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Footer content
# appears at the bottom of every page's main content
# Back to top link
back_to_top: true

footer_content: "Copyright &copy; 2024 Syazwani MZ"