title: Worldbuilding
description: A portfolio of worldbuilding with two worlds.
theme: just-the-docs

url: https://syazwaniMZ.github.io/dual-worldbuilding.github.io

aux_links:
  Template Repository: https://github.com/syazwaniMZ/dual-worldbuilding.github.io
